source('setup/trials.R')
source('setup/single-stock.R')
source('setup/read_variants.R')
source('setup/read_results.R')


NafSetup('Full_run2')
NafCond(dir='Full_run2')
NafResults('Full_run2',db_name='Full_run2.db')
NafVariants(dir='Full_run2',var.search = 'Naf-v[0-2].par')
file.copy('settings/clc-n-rev.par',to = 'Full_run2/clc-n.par',overwrite = TRUE)
NafVariants(dir='Full_run2',var.search = 'Naf-v[3-7].par')
ManSetup(dir='outn-full2',db_name ='Full_run2.db')
ManRun(dir='outn-full2')
NafReadVariants(dir='Full_run2',search.string='NF-..-.-V[0-9].restest',db_name='Full_run_res2.db')
ManResults(dir='outn-full2',db_name = 'Full_run_res2.db')
